name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@main
      - run: nix run nixpkgs#shellcheck ./upload_s3.sh
      - run: nix run nixpkgs#yamllint ./action.yml
