name: Context testing
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/push-artifact-ids@test
        with:
          s3_upload_role: ooga
          bucket: booga
          directory: ./artifacts
          allowed_branches: '["main", "test"]'

      